# Generated by Django 3.0.6 on 2020-06-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employees'),
        ),
    ]
